### ISSUE TITLE
Live Person data for reports

### ISSUE THREAD

**Issue by kiranpotladurthi** [LivePersonInc/developers-community#88] opened 2017-11-30 09:10 UTC
Hi
We want to extract Player Visit information for whom push chat (proactive chat) was not triggered due to control group criteria set for the campaign or no agent available at that time.  Can you suggest the Live Person API using which this data can be fetched from Live Person?

Our account number is: 5003492

Thanks & Regards
kiran.

**Comment by Avishaia** [comment] 2017-11-30 11:56
Hey Eden,

Avishai here, Their AM. I referred Kiran to this forum to get answers to his technical questions regarding Visit Information KPI. Please assist :) Thanks!

**Comment by EdenKupe** [comment] 2017-11-30 12:01
Will do! I'll take a look and consult with our Data teams soon.

**Comment by EdenKupe** [comment] 2017-12-06 08:54
Apologies for the delay here Kiran.

I've spoken with the relevant people in our company and have confirmed that the [Visit Information API](https://developers.liveperson.com/rt-interactions-visit-information-visit-information.html#response) includes a parameter called "campaignControl". This field indicates whether a visitor was in the control group for a campaign and thus did not receive the invitation to chat.

Let me know if there's anything else that I can help with.

**Comment by kiranpotladurthi** [comment] 2017-12-06 09:27
This seems to be a real time API and also it required visitID to be provided.  In our case, we don't the know visitID.  We want all the visitIDs for which pushchat was not triggered in a day or hour (due to control group or agent not available).  I hope you got the requirement.

**Comment by EdenKupe** [comment] 2017-12-06 09:35
Ah, makes sense! In that case, you can use the [Data Access API](https://developers.liveperson.com/data-data-access-web-session.html#eligiblecampaign). It has a parameter called controlGroupType which you can use. However, please note that this API is in Beta. Thus, please contact Avishai, your Account Manager, to further discuss using this API.

**Comment by Avishaia** [comment] 2017-12-06 09:39
Thanks for suggesting Data Acess API, Eden. This is was my suggestion as well.

@kiranpotladurthi can you please send your technical questions here after reviewing the Data Acess API option?

Thanks.

**Comment by kiranpotladurthi** [comment] 2017-12-06 10:06
Can you provide the url and query parameters to be used for this?  what values should be passed for controlGroupType ?

**Comment by EdenKupe** [comment] 2017-12-06 10:15
The way the Data Access API works is this:

When you call the API, you choose a startTime and an endTime. Once the API is called, you receive files generated for a set interval during that time (so let's say your startTime is 00:00 and your endTime is 24:00, you'd get 24 files, one for each hour). In those files, you'll see all visitors on your site as seen by our tag.

Within those files, you can search for the controlGroupType and thus see which visitor was part of a control group and which wasn't. There's no way to get back *only* the visitors who were part of the control group. You retrieve all the visitors during a certain time and use that parameter to know which were included and which weren't.

Hope that's clear, let me know if you need any more info.

**Comment by kiranpotladurthi** [comment] 2017-12-06 12:55
thank you for the explanation.  In the documentation for controlGroupType it is mentioned as below:
Type of the campaign control groups. Can be one of the following: NA, TEST, CONTROL.
Can you explain what these values mean?

**Comment by EdenKupe** [comment] 2017-12-10 14:18
Hey @kiranpotladurthi 

Thanks for your patience. I have not forgotten your issue; I am chasing down the relevant people in our R&D departments to try and figure out what these parameters mean. I will hopefully know more tomorrow and will keep you updated.

Thanks again.

**Comment by EdenKupe** [comment] 2017-12-13 13:47
Ok, got an answer!

NA = Visitor wasn't in the control group or not because no control group was set. This is the default mode, when you have not used the control group feature.

TEST = Visitor received the engagement even though a control group was set. If you set a control group at 10% of visitors, 90% of them will receive TEST since they'll see the engagement.

CONTROL = visitor did not receive the engagement because they are in the control group. If you set a control group at 10% of visitors, 10% of them will receive CONTROL since they won't see the engagement.

Hope this helps, let me know if you need anything else.

**Comment by donmanguno** [comment] 2017-12-18 17:03
Hi @kiranpotladurthi did Eden's answer help? Do you have any further questions?

**Comment by kiranpotladurthi** [comment] 2017-12-19 05:16
Hi
We are unable to check this as it requires an agreement to use this API (Beta agreement).  Once we get access to it, we will check and update you.
Also, we need Player Visit information for whom push chat (proactive chat) was not triggered due to agent not available at that time.  Can you let us know how to get this information?

**Comment by donmanguno** [comment] 2017-12-19 18:13
Hi @kiranpotladurthi.

The Visit Information API can be used to retrieve data even about visitors who have not been invited to chat. You will need to know their visitorId and sessionId, and you will need to build your own mechanism for retrieving these IDs for all of your visitors (they are available in cookies), but if you have these IDs you can use the Visit Information API with them.

https://developers.liveperson.com/rt-interactions-visit-information-visit-information.html

I am now closing this issue.

**Closed by donmanguno** 2017-12-19 18:13 UTC
