### ISSUE TITLE
Server Chat API -> exit survey results do not show in BI or custom report dashboards?

### ISSUE THREAD

**Issue by jhayes411** [LivePersonInc/developers-community#161] opened 2018-02-22 18:58 UTC
Hi dev support,
Why would exit survey questions that are submitted via the Server Chat API - method: Submit Survey Data not show up in the BI Dahsboards?  On Samsung account (60379263) the questions were created in LiveEngage in exit survey called: Custom Chat window test Exit Survey.  We can see them and the actual visitor transcript data that its being captured properly, but neither the BI Dashboard or the Custom report build will show that survey in their output.  Is this because its being submitted via the API listed above? Is this just a side effect of using the API?  In other words, if its not submitted thru our out of the box exit survey, its not going to show up in either reporting dashboard? 
I have attached the transcript with the columns of that particular survey showing its being captured (columns IP thru JF).
[SS-chatbot-transcripts2.csv.xlsx](https://github.com/LivePersonInc/developers-community/files/1749170/SS-chatbot-transcripts2.csv.xlsx)

thnx,
Jim

**Comment by donmanguno** [comment] 2018-02-28 20:04
Hi @jhayes411, this does not strike me as expected behavior. I'm performing some tests to see if I can reproduce it.

**Comment by jhayes411** [comment] 2018-03-01 16:24
Any updates? i would agree that its seems odd, but maybe a side effect of the chat server API?

**Comment by donmanguno** [comment] 2018-04-06 02:53
Hi Jim, I'm closing this issue since you're opening a case. Send me the case number when you get a chance and I'll assist there.

**Closed by donmanguno** 2018-04-06 02:53 UTC
